### ISSUE TITLE
trying to use kraken-powershell as an azure automation module

### ISSUE THREAD

**Issue by cconner100** [Kevin-Bronsdijk/kraken-powershell#1]
When I upload the zip file with the needed files, I get the following error

Error extracting the activities from module kraken-powershell. Extraction failed with the following error: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: Cannot import the module of name kraken-powershell, as the module structure was invalid.

Any ideas?

**Comment by Kevin-Bronsdijk** [comment]
Hi, the content of the package should me modelled based on the following criteria.

https://azure.microsoft.com/en-us/blog/authoring-integration-modules-for-azure-automation/

Let me know if it works. Sounds interesting to run it within azure automation.

**Comment by cconner100** [comment]
thanks looked at this but its still not making any sense to me, in the
example it does not show how to package up a specific dll such as yours and
all the needed additional dll's do you have any suggestions on this?

**Comment by Kevin-Bronsdijk** [comment]
I've tried the following with success (and therefore we can conclude that the documentation is wrong) 

1) create a new folder called "kraken.powershell" 
2) Put the files kraken.dll, kraken.powershell.dll, Newtonsoft.Json.dll and System.Management.Automation.dll within this folder
3) zip the folder and name it kraken.powershell.zip (this includes the folder, which is important)
4) Upload the file and you should be able to see the commands.

![krakenps](https://cloud.githubusercontent.com/assets/10368555/24644334/27261c66-193d-11e7-871f-1abfb2e404c5.png)
